# Generated by Django 4.0 on 2021-12-21 13:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
